### ISSUE TITLE
Auto release with goreleaser and GitHub workflow

### ISSUE THREAD

**Issue by erdaltsksn** [isacikgoz/gitbatch#109]
I'm using [goreleaser](https://goreleaser.com) with [GitHub workflow](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions) to automatically release my go applications.

This can be beneficial for this because of the features following:

- auto-generated changelog
- homebrew support
- easy cross-platform compiling

I'm really happy especially with the homebrew update and changelog generation.

I'm happy to implement this if you want.

The example repository that uses this workflow:

- [random](https://github.com/erdaltsksn/random)
- and its brew repo: [homebrew-tap](https://github.com/erdaltsksn/homebrew-tap)

**Comment by isacikgoz** [comment]
Thanks a lot @erdaltsksn 🎉 I would love to see this happen, sorry for the late answer BTW. Please feel free to open a PR for this 👍
