### ISSUE TITLE
App shows non-existing (deleted) remote branches

### ISSUE THREAD

**Issue by utkuufuk** [isacikgoz/gitbatch#19]
#### Remote Repo
![screenshot from 2018-12-03 19-55-21](https://user-images.githubusercontent.com/15212283/49388682-8e728f80-f735-11e8-87b3-025ca2cf8d4f.png)
#### Gitbatch
![screenshot from 2018-12-03 19-57-14](https://user-images.githubusercontent.com/15212283/49388730-ab0ec780-f735-11e8-9d90-5ee47fd0d42f.png)

**Comment by utkuufuk** [comment]
The issue doesn't go away even after `git fetch` (Git version: 2.17.1)

**Comment by isacikgoz** [comment]
Can you copy output of `git branch -r`

**Comment by utkuufuk** [comment]
origin/HEAD -> origin/master
    origin/feature
    origin/master
    origin/python

**Comment by isacikgoz** [comment]
You should use `git fetch --prune` to remove non-existing branches in the remote as [documentation](https://git-scm.com/docs/git-fetch#git-fetch---prune) says. 
The question is; should the app add --prune option by default?

**Comment by utkuufuk** [comment]
I don't think it should. Maybe you can display those remote branches in a different color or put a special character next to them?

**Comment by isacikgoz** [comment]
see aa6f0cf9a44f502fe41aecf9ed3f5ddbb8e20a71
