### ISSUE TITLE
Make "Pull" the default mode or make it configurable

### ISSUE THREAD

**Issue by utkuufuk** [isacikgoz/gitbatch#22]

**Comment by isacikgoz** [comment]
this is a subtle issue, but I would like to hear alternative voices. For me, fetch is safe but to be more practical I understand that pull can be the first option. I will leave this issue open for a while and lets see if we will get more opinions.

**Comment by isacikgoz** [comment]
see ad96d97d0262df1e1ab3b054b8d2600c8d821d42
