### ISSUE TITLE
ssh 

### ISSUE THREAD

**Issue by d1medeiros** [isacikgoz/gitbatch#48]
hi, i'm start today in this tool and im in love. But i can sync with remote repository because de tool cant find my keys. can u help me

**Comment by isacikgoz** [comment]
hey @d1medeiros thanks for checking in! Does fetching or pulling gives an error? If so, can you provide the output or screenshot?

By default, gitbatch uses your git configuration files. If you configured your remote connection with ssh, it will use ssh keys with remote. is your ssh keys are valid with remote? can you check them. (public keys) 

by default, ssh keys are stored in .ssh folder in your home directory. I always tested with that configuration and never had an issue with ssh connection.

If there is an error in your ssh configuration; you can re-configure it. Here are the guides for 3 mainstream remote providers:
  - [Connecting to GitHub with SSH](https://help.github.com/articles/connecting-to-github-with-ssh/)
  - [GitLab and SSH keys](https://docs.gitlab.com/ee/ssh/)
  - [BitBucket Set up an SSH key](https://confluence.atlassian.com/bitbucket/set-up-ssh-for-git-728138079.html)

**Comment by isacikgoz** [comment]
@d1medeiros I was digging the ssh authentication and found something. Can you tell me the output of `echo $SSH_AUTH_SOCK` command? If the output is nothing; It might be that ssh-agent may not be running.

I will patch this situation with handing over to actual git to authenticate and fetch/pull. But this will be a temporary solution.

**Comment by d1medeiros** [comment]
hi @isacikgoz ! I'm sorry for take to long to answer you. I got my keys on .ssh as u said and the echo command output a path with` /private/tmp/.../Listeners`
I'll keep looking because I'm pretty sure that is something that I did wrong and I like a lot the idea of Gitbash

**Comment by d1medeiros** [comment]
hi @isacikgoz , as i was thinking, i was the problem. all i had to do was` ssh-add ~/.ssh/id_rsa`
thankss
