### ISSUE TITLE
Feature: Support page up/down and home/end navigation

### ISSUE THREAD

**Issue by gavinws** [isacikgoz/gitbatch#49]
It would be nice to be able to page up/down and home/end for navigation in the repo list, or some similar key combination (shift + arrows, or vim bindings, etc).

**Comment by isacikgoz** [comment]
Hi @gavinws thanks for the suggestion. Currently the library I use for key inputs does not support key sequences(vim keys may not be easy to do), but key combination seems applicable. I will look at this request.

**Comment by isacikgoz** [comment]
hey @gavinws I added page up/down and home/end for navigation in the repositories list. you can check it at `develop` branch

**Comment by isacikgoz** [comment]
hi @gavinws you can try #54 I added your request. Thanks for the feedback!

**Comment by gavinws** [comment]
Thank you for adding that! It works great on 0.3.0.
