### ISSUE TITLE
Homebrew Installation

### ISSUE THREAD

**Issue by nexeck** [isacikgoz/gitbatch#55]
It would be cool, to be able to install gitbatch with homebrew on macOS.

**Comment by isacikgoz** [comment]
thanks for the feedback @nexeck I was thinking on that too. After I handle my dependencies with go modules, I will work on distribution via brew etc.

**Comment by isacikgoz** [comment]
I've just implemented this and it is on the README.md. Also, feel free to open a new issue if you have another request.
