### ISSUE TITLE
tab behaviour

### ISSUE THREAD

**Issue by WhoMeNope** [isacikgoz/gitbatch#64]
This might be intended, but seems a bit inconsistent.

In the main screen tab is used to focus on a repository, but after that it cycles through the different panes (commits, status, remotes, branches, stash).
I would expect tab to return me to the main screen, rather work in a zoom in/zoom out way, then change behaviour completely.

**Comment by isacikgoz** [comment]
I was struggling to decide on the keybindings to focus and focus back. I think I need feedback and suggestions to more consistent keybindings. 

Scrolling through panes via `tab` key is used on many similar applications. If we use `tab`for just switching screens, then, would h/l buttons will be enough to scroll through panes?

**Comment by isacikgoz** [comment]
fixed with #68
