### ISSUE TITLE
Backup/Restore remotes 

### ISSUE THREAD

**Issue by Vafa-Andalibi** [isacikgoz/gitbatch#70]
I personally have several different remotes for each repository which is quite time-consuming if I want to set them up in another machine. Do you think adding a backup/restore feature is useful for addressing such issues?

**Comment by isacikgoz** [comment]
hey @Vafa-Andalibi, gitbatch does not store any information of repositories in any sense. And I don't have any plan to do so. 

But you can keep the config file separately which holds the remote configuration.

The configuration can be found at the file: `/path/to/your/repo/.git/config` You can move that file to another machine and you won't need to re-configure remotes.

**Comment by Vafa-Andalibi** [comment]
Thanks for the reply, so I think I should write a backup/restore script for that.
