### ISSUE TITLE
Feature request: batch branch checkout

### ISSUE THREAD

**Issue by hendricha** [isacikgoz/gitbatch#72]
At my workplace we have a rather large project, that contains 10+ repositories (don't ask, not my idea), and sometimes when a larger feature is being implemented, we have to work in multiple repositories, therefore they all will have the dedicated feature branch. What I would like is the option to batch switch to a same named branch in multiple repositories.
eg like this:
Go into Branch Switch mode -> select relevant repositories like in other modes -> Start either opens a branch list (that shows all common branch names in selections) or there is a simple text input -> this check out that branch in all selected repositories

**Comment by isacikgoz** [comment]
I am considering to add this feature, but I need scenarios that explain me how it should work. I also found it useful after I discussed with some of my colleagues.

**Comment by isacikgoz** [comment]
Hey @hendricha, I've just implemented this and it's merged to master. Also, feel free to open a new issue if you need another feature.

The usage is:
<ctrl-b> to select branch to checkout
<c> checkout mode
<space> mark repos you want to checkout
<enter> start batch job

**Comment by mhagnumdw** [comment]
@isacikgoz, thanks for the answer above! I was looking for it.

If the branch does not exist, is it possible to prevent it from being created?
