### ISSUE TITLE
ERROR 53

### ISSUE THREAD

**Issue by philipperemy** [isacikgoz/gitbatch#79]
I was using the tool when this error happened:

```
ERRO[0053] application quitted with an unhandled error.  error="There is no job with given repoID"
```

**Comment by isacikgoz** [comment]
thanks for the feedback @philipperemy Can you provide me the steps to reproduce this issue?

I suspect that the queue started before the app loaded all repositories.

**Comment by philipperemy** [comment]
Hum not sure how I did that :)

**Comment by isacikgoz** [comment]
I am closing this issue, both you and me are not able to reproduce it, if you face it again feel free to open a new issue.

**Comment by philipperemy** [comment]
@isacikgoz ok!
