### ISSUE TITLE
undefined variable

### ISSUE THREAD

**Issue by tcondit** [isacikgoz/gitbatch#80]
Running `➜ go get -v -u github.com/isacikgoz/gitbatch` on MacOS, things stopped at this error:

> /Users/timc/go/src/github.com/isacikgoz/gitbatch/core/command/pull.go:127:20: undefined: memory.ErrRefHasChanged`

Sure enough, it's not defined:

> ➜ pwd
> /Users/timc/go/src/github.com/isacikgoz

> ➜ rg ErrRefHasChanged
> gitbatch/core/command/pull.go
> 127:		} else if err == memory.ErrRefHasChanged && pullTryCount < pullMaxTry {

**Comment by jotarada** [comment]
I have the same problem. Using Ubuntu 18

```
go get -u github.com/isacikgoz/gitbatch
# github.com/isacikgoz/gitbatch/core/command
go/src/github.com/isacikgoz/gitbatch/core/command/pull.go:127:20: undefined: memory.ErrRefHasChanged
```

**Comment by isacikgoz** [comment]
Thanks for the feedback @tcondit and @jotarada I will look at this in a couple days. I guess it is a dependency management issue. Which I was avoiding for a while. I guess I need to deal with it :)

**Comment by tarkah** [comment]
@isacikgoz I'm working on packaging this for Nix, ran into the above issue. I believe #81 fixes this.

**Comment by isacikgoz** [comment]
@tarkah  just fixed it and it's merged to master. Please let me know if you still the issue. Also, feel free to open a new issue.
