### ISSUE TITLE
Installation wiki page outdated

### ISSUE THREAD

**Issue by utkuufuk** [isacikgoz/gitbatch#90]
https://github.com/isacikgoz/gitbatch/wiki/Installation

Above page points to v0.4.1, and when I customize the script like this:
``` sh
curl -OL https://github.com/isacikgoz/gitbatch/releases/download/v0.4.3/gitbatch_0.4.3_linux_amd64.tar.gz
tar xzf gitbatch_0.4.3_linux_amd64.tar.gz
```
I get the following error:
``` txt
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

OS: Ubuntu 18.04

**Comment by isacikgoz** [comment]
Hey @utkuufuk , thanks for the feedback. v0.4.3 was just a tag for indicating the go.mod. However, I added binaries for this tag. Now you can download them.
